AllCops:
  Exclude:
    - 'spec/**/*'
    - 'bin/*'
    - 'test/**/*'
    - 'db/*'
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'
  SuggestExtensions: false

Documentation:
  Enabled: false
